### ISSUE TITLE
Seeding

### ISSUE THREAD

**Issue by raphaelavalos** [PettingZoo-Team/PettingZoo#156]
Hello,
While trying to use multi-walker I realized that there was no seed method even though the method is present in the base env. Is it a design choice?
I think that adding this method to all the environments would be nice. (And also on the RLlib wrapper)
Let me know what you think

**Comment by weepingwillowben** [comment]
So we chose to add seeding as a environment parameter rather than a method. 

Is there some reason it is easier or more useful to seed using a method rather than a parameter?

Thanks for your feedback.

**Comment by raphaelavalos** [comment]
Thanks for the quick response.
There are two main reasons I think it would be a nice addition.
- It will be more gym friendly which would help the adoption this library.
- When setting the seed for numpy, random and torch the env might already be created (like in rllib).
What do you think?

**Comment by weepingwillowben** [comment]
Thanks for the comments, 

* A seeding function will indeed be more gym-like. We were hoping that the parameter would be an easier model of seeding to understand, but we will keep in mind that you found this harder to work with, and we will keep this issue alive so that other people can comment on this question. 
* As for the concern about the global random, numpy and tf seeds, our environments are all tested to be 100% independent of these seeds. Instead, (like gym) they use an internal `numpy.random.RandomState` which is unaffected by the global random state which you change with `numpy.random.seed()`. So you should not be concerned about when or whether you set the global seeds.

**Comment by justinkterry** [comment]
So having the seed as an argument was a deliberate design choice. Many things we've done with PettingZoo were intended to address issues we had with Gym, including:

-Thorough and well organized documentation, i.e. https://pettingzoo-team.github.io/PettingZoo/sisl/multiwalker
-Built in tests of environments for API compliance, including helpful warnings (this is something Gym still doesn't have, though a skeleton of this was added to stable baselines awhile back)
-Very comprehensive CI testing
-Comprehensive and informative warnings and error messages
-Making many environment arguments the standard, because it promotes better reproducibility, more experimentation, and so on. Gym environments outside of Gym proper have embraced this, and you can see this with say the number supported in SISL.


Having a ton of environment arguments by default, in addition to a seperate seed function, doesn't seem right. Additionally, because of how you have to call the seed function, putting it as an argument makes a lot more sense to me to begin with.

**Comment by raphaelavalos** [comment]
Hello,

What I meant with my second point is that I always use a seed function in my code that sets the seed for everything (numpy, random, torch, and the env). This is also what is done in RLlib, which lets me believe that it is a common practice. I think that in the end, this might jeopardize PettingZoo adoption if it is the only library that doesn't offer the seed method.

An option would be to add the seed function and a warning that PettingZoo best practices for reproducibility recommend setting the seed in the constructor. 

Also, in the documentation of multiwalker the seed argument is missing.

**Comment by weepingwillowben** [comment]
Added the seed argument in PR #165

**Comment by justinkterry** [comment]
@raphaelavalos we've straightened out the seeding stuff you mentioned (thank you for that), but what a sensible inclusion of seeding in the RLlib wrapper looks like is unclear. Did you have a specific idea?

**Comment by raphaelavalos** [comment]
Your welcome ! In RLlib the seed is set [here](https://github.com/ray-project/ray/blob/322f12600f1cbedac12a700157593004082fca17/rllib/evaluation/rollout_worker.py#L385-L393).

The only thing that I would add in the wrapper (`rllib/env/pettingzoo_env.py`) is a seed method that calls the seed method of the aec_env. Let me know what you think :)

**Comment by justinkterry** [comment]
@raphaelavalos This covers what you're looking for right? https://github.com/ray-project/ray/pull/10847#pullrequestreview-490875421

**Comment by raphaelavalos** [comment]
Yep exactly :) Thanks !
