### ISSUE TITLE
AttributeError: module 'pettingzoo.butterfly.prison' has no attribute 'manual_control'

### ISSUE THREAD

**Issue by dgauraang** [PettingZoo-Team/PettingZoo#167]
Code:
```
import pettingzoo
from pettingzoo.butterfly import prison


if __name__ == '__main__':
    prison.manual_control()
```
I'm just trying to manually control the game according to the code in the link below.
https://www.pettingzoo.ml/api

**Comment by weepingwillowben** [comment]
Thanks for raising this issue. The documentation is fixed to specify that you need to import the version of the environment, `prison_v1`. In addition, the code was broken so that this does not quite work either. 

The solution is in a PR #168 and will be released very soon (a couple of days). There are also tests to make sure the issue will not appear again. 

In the meantime, you can use an undocumented way of accessing prison's manual control:

```
import pettingzoo
from pettingzoo.butterfly.prison.manual_control import manual_control


if __name__ == '__main__':
    manual_control()
```
