### ISSUE TITLE
Caching of dependencies in CI

### ISSUE THREAD

**Issue by ndyashas** [PettingZoo-Team/PettingZoo#173]
I noticed that a large amount of time in CI is used while installing and building wheels (especially OpenCV). I think the caching option from Travis could be of great help in reducing the build time. [Link here](https://docs.travis-ci.com/user/caching/#pip-cache).

**Comment by weepingwillowben** [comment]
The thing that always seems to take forever for me is building multi_agent_ale_py. Because I haven't released pre-built wheels for that yet. So that is probably much higher priority anyways, because it affects users. I made an issue for it [here](https://github.com/PettingZoo-Team/Multi-Agent-ALE/issues/3) and I'll put that high on my todo list. 

After that is done, we will see if caching is needed.

**Comment by weepingwillowben** [comment]
I added a PR with this simple fix you pointed out. Lets see if it works.

**Comment by ndyashas** [comment]
I just noticed that it works pretty fine for the Linux OS. Not sure if it is doing its job with the macOS though.
