### ISSUE TITLE
Examples of RLlib contrib/MADDPG trained in PettingZoo environments (e.g. prison)

### ISSUE THREAD

**Issue by rallen10** [PettingZoo-Team/PettingZoo#182]
Are there examples of using RLlib's MADDPG implementation with PettingZoo environments similar to the [TwoStepGame example](https://github.com/ray-project/ray/blob/master/rllib/examples/two_step_game.py)? For the TwoStepGame, their is an environment config `actions_are_logits` that seems specifically designed to work with MADDPG, but I don't see a similar config for the prison environment.

**Comment by justinkterry** [comment]
So I'm actually the maintainer of RLlib's MADDPG implementation. MADDPG is a mixture of two things- it's a centralized critic method based on DDPG, and it's OpenAI's specific implementation of that with a lot of weird stuff pertaining to continuous/discrete action space conversions beyond what you mentioned. Straight MADDPG basically doesn't work for anything other than MPE environments due to a bunch of weird stuff, and the documentation basically says it doesn't work. Standard centralized critic with DDPG works at all, but not remarkably well. What works the best on all this stuff is parameter sharing. We have a documentation PR with examples for plain centralized critic and parameter sharing and some other stuff open on RLlib now: https://github.com/ray-project/ray/pull/9722, that I think will get merged soon.

We also have a paper on parameter sharing that's fairly relevant: https://arxiv.org/abs/2005.13625, with a bunch of code. The repo for it has the results of MADDPG runs, it performs orders of magnitude worse. We're going to add the comparison to the paper soon since people keep asking about it.

**Comment by rallen10** [comment]
@justinkterry thanks for the quick reply. Yeah I agree that MADDPG essentially doesn't work for anything other than MPE. Unfortunately it is still one of the most cited papers in multiagent RL so when I'm working on experiments for a new paper, there is strong motivation to compare against MADDPG (even though MADDPG doesn't work). I appreciate you putting together the MADDPG implementation for RLlib. Did you ever run it on PettingZoo envs?

**Comment by justinkterry** [comment]
I think we ran it on prison and/or pistonball at one point, @weepingwillowben or @lssr will know where that code went. 

Also I didn't actually add MADDPG to RLlib, a guy in montreal did and abandoned it and awhile later I took over maintenance.

**Comment by justinkterry** [comment]
Actually, we don't have any code like what you're looking for. We became convinced that the RLlib implementation of MADDPG was cursed, and us and some people in germany couldn't figure out why after a really long time, so we used the reference OpenAI repo for MADDPG and ported it to apply to the original API of the SISL environments. This all happened before PettingZoo was in a state where we could actually use it. That being said, it shouldn't using RLlib's MADDPG with a PettingZoo env be super straight forward?

**Comment by rallen10** [comment]
If I fork PettingZoo and make minor modifications, I think it is pretty straightforward to apply MADDPG to PettingZoo envs. I am thinking it is a matter of adding something akin to [`actions_are_logits` config in the TwoStepGame example](https://github.com/ray-project/ray/blob/09d4a3241ff872866e6c0573abe24305ab8deeab/rllib/examples/env/two_step_game.py#L40). I wanted to see if there was a way to do it without forking PettingZoo (e.g. if there was some other config for sampling MADDPG that I wasn't aware of)

**Comment by weepingwillowben** [comment]
I'm not quite clear on exactly what you want to do, but doesn't converting logits to discrete actions introduce a massive amount of socasticity into the learning process? Because the trainer does not know what the sampled discrete action was chosen during that time step? This is a consideration we encountered when trying to do what you are doing. 

If you still want to proceed, you can execute this functionality with the `action_lambda` wrapper in [SuperSuit](https://github.com/PettingZoo-Team/SuperSuit). I put some code which accomplishes this [here](https://gist.github.com/weepingwillowben/9cd900113a47a5145288d456ef2aaa67).

**Comment by rallen10** [comment]
@weepingwillowben thanks for the pointer to `action_lambda`; that might be what I need. 

For more context, I am trying to do a proof-of-concept of using the RLlib implementation of MADDPG to train in PettingZoo environments. As a starting point, I am trying to train MADDPG in a 2-floor prison-v1 environment. 

In short, I am trying to run the [rllib pettingzoo env example](https://github.com/ray-project/ray/blob/master/rllib/examples/pettingzoo_env.py) but substituting "contrib/MADDPG" in place of "PPO" as the algorithm. However when I try a very simple switch in algorithms, I get the error
```
assert self.action_spaces[self.agent_selection].contains(action), "action is not in action space"
AssertionError: action is not in action space
```

**Comment by rallen10** [comment]
@weepingwillowben the `action_lambda` seems to be on the right track, but I still haven't got it working in the multi-agent prison environment.

First I had to modify [your code](https://gist.github.com/weepingwillowben/9cd900113a47a5145288d456ef2aaa67) a bit because I was getting errors about `reward_range` and `metadata`. See mods below:
```
def prison_v1_env_creator(env_config):
    # create raw PettingZoo environment
    env = prison_v1.env(
        num_floors=_NUM_FLOORS,
        vector_observation=_VECTOR_OBSERVATION)

    # wrap env with RLlib-compatible PettingZooEnv
    env = PettingZooEnv(env)

    # If actions are logits (e.g. maddpg) use an additional action wrapper
    if env_config["actions_are_logits"]:
        env.metadata = {'render.modes': []}
        env.reward_range = (-float('inf'), float('inf'))
        env = action_lambda(env,
            lambda action, action_space: sample_softmax(action),
            lambda action_space: Box(shape=(action_space.n,), low=-_LOGIT_BOUND, high=_LOGIT_BOUND))

    return env
```

After that, I'm still getting an error that seems related to the fact that `action_lambda` does not seem to generalize to multiagent environments:
```
ValueError: Have multiple policies {'prisoner_0': <ray.rllib.contrib.maddpg.maddpg_policy.MADDPGTFPolicy object at 0x7f23bff1b880>, 'prisoner_1': <ray.rllib.contrib.maddpg.maddpg_policy.MADDPGTFPolicy object at 0x7f23ad14ca90>, 'prisoner_2': <ray.rllib.contrib.maddpg.maddpg_policy.MADDPGTFPolicy object at 0x7f238470b370>, 'prisoner_3': <ray.rllib.contrib.maddpg.maddpg_policy.MADDPGTFPolicy object at 0x7f2384520160>}, but the env <action_lambda<ray.rllib.env.pettingzoo_env.PettingZooEnv object at 0x7f23bff0cbe0>> is not a subclass of BaseEnv, MultiAgentEnv or ExternalMultiAgentEnv?
```

I'll keep working and see what I can come up with but an advice is appreciated

**Comment by rallen10** [comment]
I think I figured it out! My most recent problem was that I was using the wrong `action_lambda`. I needed `supersuit.aec_wrappers.action_lambda` but I was using `supersuit.gym_wrappers.action_lambda`. For future reference, here is the crux code for using RLlib's contrib/MADDPG algorithm on the prison environment:

```
from gym.spaces import Box
from supersuit.aec_wrappers import action_lambda
_NUM_FLOORS = 2
_LOGIT_BOUND = 1e6
def prison_v1_env_creator(env_config):
    env = prison_v1.env(num_floors=_NUM_FLOORS)

    # If actions are logits (e.g. maddpg) use an additional action wrapper
    if env_config["actions_are_logits"]:
        env = action_lambda(env,
            lambda action, action_space: sample_softmax(action),
            lambda action_space: Box(shape=(action_space.n,), low=-_LOGIT_BOUND, high=_LOGIT_BOUND))

    # wrap env with RLlib-compatible PettingZooEnv
    env = PettingZooEnv(env)

    return env
```

**Comment by weepingwillowben** [comment]
For future reference, the correct supersuit usage is this:

```
from supersuit import action_lambda
```

The system will automatically detect whether you are using a gym wrapper or a pettingzoo wrapper.
