### ISSUE TITLE
Agent Death Problems

### ISSUE THREAD

**Issue by justinkterry** [PettingZoo-Team/PettingZoo#221]
So we’ve been contemplating how to sanely fix everything that’s caused the recent wave of issues regarding environments with agent death. The fundamental problem is how we’re handling agent iter. So we’re going to fix agent_iter, and add several more minor API improvements relevant to agent death that we probably should’ve done before.

The primary problem with agent_iter is that it turns out that having a single wrapper that takes care of it for all environments can’t be done in a reasonable way for all types of environments and ones with agent death. So we’re going to move it into individual environments and put frequently used things in helper functions. That’s the big change.

We’re also going to remove dead agents from observations/rewards/dones/infos/agents and put them behind reset, force the post-terminal steps to only accept None, and add another attribute listing all possible agents (since agents will be mutable). Those shouldn’t affect you guys if we do them right, and in retrospect should’ve been done to begin with. 

All this should allow for the clean handling of any conceivable variable agent scenario (not just death)  This should also result in modest performance improvements. We’ll also update the RLlib wrapper and SuperSuit accordingly, and add new tests pertaining to these changes. 

This should probably take us like a week to fully sort out. We obviously may introduce new bugs in the process, but this will solve the real underlying issues. Where a lot of this comes from is that we study purely cooperative emergent behavior, so things like optimally handling low level reward manipulation was at the top of our minds in development, whereas we clearly didn't contemplate every aspect of agent death.

@rallen10 @jdpena

**Comment by jdpena** [comment]
I thought this was worth mentioning: my colleague was able to get [knights_archers_zombies](https://www.pettingzoo.ml/butterfly/knights_archers_zombies) to work without agent death being an issue. Upon closer inspection, we learned that agents have their observations "blacked-out" using the `black_death` environment parameter, which prevents the agent from "dying". If set to False, I presume agent death can cause similar issues to those documented in #209. If a parameter like `black_death` is added to `tiger-deer`, then it could also prevent the agent death issue. I just don't know how feasible it would be. 

Interestingly, I'm running experiments with `battle` and `battlefield` from  MAgents, and I don't seem to be having agent death issues (so far). This could mean that `tiger-deer` is the real issue here, or I haven't experienced agent death in the other environments yet. I'll keep you posted.

Thanks again for all your support.

Cheers.

**Comment by justinkterry** [comment]
#238 fixes this
