### ISSUE TITLE
Invalid Observation Values with MAgent Envs

### ISSUE THREAD

**Issue by jdpena** [PettingZoo-Team/PettingZoo#222]
The default config in `battle` and `battlefield` causes the observation values to be outside the `[0,2]` allowed range, leading to a ValueError. Note the `-0.105` in the error below. The obs shapes are correct. 

```
ValueError: ('Observation outside expected value range', Box(6929,), array([ 0.    ,  0.    ,  0.    , ..., -0.105 ,  0.3875,  0.45  ],
```

I set `step_reward`, `dead_penalty`, and `attack_penalty` to be 0 (or any value between `[0,2]`) and it fixed the issue.

Edit: it appears all MAgent envs suffer from this issue except `tiger-deer`.

**Comment by yutaizhou** [comment]
To piggy back off this question, can someone help me understand the observation of battle or battlefield? The obs_space is (13,13,41), which represents:
empty 1,
obstacle 1,
red 1,
blue 1,
minimap_red 1,
minimap_blue 1,
binary_agent_id 10,
one_hot_action 21,
last_reward 1,
agent_position ??

Which leave us with 38 of the 41 filters of axis=2 explained. I am not sure what agent_position means, so i don't know if that description would take up 3 filters to represent.

**Comment by justinkterry** [comment]
We'll reply to this soon, but let me first mention that we're planning to overhaul magent observations and documentation in the next few weeks (after the death thing is fixed)

**Comment by yutaizhou** [comment]
Here is my temporary workaround for OP's issue:

```
env = battlefield_v1.env()
default_space = env.observation_spaces['red_0']
desired_space = GymBox(low = -default_space.high,
                 high = default_space.high,
                 shape = default_space.shape,
                 dtype = default_space.dtype)
for agent_id in env.observation_spaces.keys():
      env.observation_spaces[agent_id] = desired_space
```

**Comment by yutaizhou** [comment]
actually, The bounds are probably better off being inf and -inf, since Battle can have +5 rewards or neg reward. That is if no further reward modification is done by users, e.g. sum up all rewards from agents within a cycle and use it as team reward.

https://www.pettingzoo.ml/magent/battle

**Comment by weepingwillowben** [comment]
Thanks for pointing out the incorrect observation bounds. It seems as though the culprit is the last_reward, and as the minimap observations are bounded between 0 and 2, and all other observations seem to be bounded between 0 and 1. We are not big belivers of infinite bounds, so perhaps reward observations can just be bounded properly. 

As for what the observation is composed of, agent_position, it is the normalized x and y coordinate (from [0-1) on the grid. This leaves 1 more unexpected slot. When I determined the observation space of magent, I did so by looking through [here](https://github.com/PettingZoo-Team/MAgent/blob/master/src/gridworld/GridWorld.cc#L292), so I was bound to make mistakes.

Looking at this more carefully to try to account for this extra dimension of the data, I found that both the existence and HP of an agent are reported. And obstacles and empty values are reported in the same channel. So it goes like:

empty/obstacle 1,
red 1,
red_hp 1,
minimap_red 1,
blue 1,
blue_hp 1,
minimap_blue 1,
binary_agent_id 10,
one_hot_action 21,
last_reward 1,
agent_position 2

I'll make sure to update the documentation shortly.

As for fitting the observations in the bounds, the easiest way would be to simply scale the overall magnitude of rewards so that the last reward is always between 0 and 1. And complaints about this approach?

**Comment by weepingwillowben** [comment]
Actually, I realized the downside, the problem is that we allow users to specify rewards. The better solution is just to change the bounds of the observation space for the reward channel only.

**Comment by yutaizhou** [comment]
I think reward should be something that is consistent when passed from one timestep to the next, so I prefer your last solution as opposed to normalizing rewards to be in [0,1] when received as last_reward in an observation. 
This would just require tempering with the Gym Box space like: `Box(low=np.array([-1.0, -2.0]), high=np.array([2.0, 4.0]), dtype=np.float32)`

**Comment by yutaizhou** [comment]
And thanks for looking into the feature description of the observations! Yeah documenting that will help tremendously.

**Comment by yutaizhou** [comment]
@weepingwillowben sorry but I need to clarify the observation each agent gets in Battlefield. We are trying to pick out global information for a centralized critic, so it's absolutely crucial that we grab the right feature. 
Some questions:
1. Is what you wrote here the exact ordering of the 41 observation filters? This is so I can know which feature I am grabbing when I slice into the 41 dim second axis of 13x13x41
2. Are the minimaps the only global features an agent can observe? Is there a way to access things like list of agents along with their health, team affiliation, and position? Just trying to think of what we can feed into the centralized critic which is meant to take global information during training. 
```
empty/obstacle 1,
red 1,
red_hp 1,
minimap_red 1,
blue 1,
blue_hp 1,
minimap_blue 1,
binary_agent_id 10,
one_hot_action 21,
last_reward 1,
agent_position 2
```

**Comment by weepingwillowben** [comment]
So I am trying to be precise about the order of the values in the observation channels. However, I found this order by reading 300+ lines of convoluted c++ code, so I cannot be absolutely certain. I recommend you look at the values in those channels and make sure they seem reasonable. For example, I ran the following code:

```
print(np.stack(observations[agent][:,:,2] for agent in parallel_env.agents).min(0))
```
And you can tell that the current agent health is at the center of that map, allowing you to get the health of that agent.

I also ran
```
print(np.stack(observations[agent][:,:,4] for agent in parallel_env.agents).max(0))
```
And realized that the current agent is always in the red map and never in the blue map. I missed that the [make_channel_trans](https://github.com/PettingZoo-Team/MAgent/blob/master/src/gridworld/GridWorld.cc#L897) function reorders the agent so that the current agent always ends up in the first set of channels. Which means that the observation really is:

```
obstacle/off the map 1,
my_team 1,
my_team_hp 1,
my_team_minimap 1,
other_team 1,
other_team_hp 1,
minimap_other_team 1,
binary_agent_id 10,
one_hot_action 21,
last_reward 1,
agent_position 2
```

As for your other questions, 

Yes, the minimaps and the agent_position are the only global information in the observation. Note that we plan to expose the `minimap` magent configuration, which disables both of these values.

There is no immediate way to easily collect the global information. Unfortunately, collecting these values directly would mean extending both the MAgent  c++ API and the python API and the pettingzoo API for magent, which is a bit much. 

If you really need these values immediately, this is how you might collect them:

Position is encoded in the last two channels (duplicated across all entries). 

The health of an agent can be collected as the center of channel 2.

team association is encoded in the agent name. For example, `red_<n>` means the agent is on team red

**Comment by yutaizhou** [comment]
This helps tremendously, and certainly belong to the docs. Thank you for the explanation!

**Comment by jdpena** [comment]
Looks like https://github.com/PettingZoo-Team/PettingZoo/pull/234 fixes this. I'll reopen if necessary.
