### ISSUE TITLE
Where are the baselines?

### ISSUE THREAD

**Issue by daanklijn** [PettingZoo-Team/PettingZoo#226]
The [PettingZoo paper](https://openreview.net/pdf/e090b9c29b966a0228fafae1c76893a45eec67ee.pdf) (which is still under review) states the following in section 6:

_All environments implemented in PettingZoo include baselines to provide a general sense of the difficulty of the environment, and for something to initially compare against._ 

Are these baselines already available? And if so, where can we find them?

**Comment by justinkterry** [comment]
So the answer to that question is a bit complicated. For the classic environments, benchmarks already exist elsewhere. Same for the MAgent, MPE and SISL environments (in the papers introducing the environments), though we've made numerous bug fixes to those so the results won't be perfectly comparable. MAgent and SISL have more scheduled as well. This only leaves Atari and Butterfly. The Atari environments we introduce in dedicated paper on the multiplayer extension to the arcade learning environment that's under review at AAMAS, which contains the benchmarks. We can't update the paper on Arxiv due to AAMAS' new stupid Arxiv policy, but if you email me I can send you a copy with the graphs if you need it and the git repo with the policies. The PettingZoo paper you've linked introduces benchmarks for the butterfly environments, and the relevant code is in the supplemental materials for the submission. There's some small issues with those experiments we're trying to clean up with those though, we'll update the paper on Arxiv when that's done, probably later this week.
