### ISSUE TITLE
How could I get the agent_selection attribute when I am in the parallel_env() mode ?

### ISSUE THREAD

**Issue by nevertiree** [PettingZoo-Team/PettingZoo#292]
Hi ~

I would like to get the available action space when I am in the parallel_env() mode. Howere, the parallel_env doesn't support some functions / attributes like agent_selection, so how could I get the available action space of each agents ?

Thanks !

**Comment by weepingwillowben** [comment]
Hi, I'm glad you found our library

To answer your question, the parallel_env does not have an agent_selection because all living agents are selected at once.

Instead, if you want to get the names of all live agents, you can just look at the list `env.agents`. If you want to get the names of all agents that can ever exist, you can use `env.possible_agents`.

If you want to learn more about the parallel API, refer to the documentation [here](https://www.pettingzoo.ml/api#parallel-api).

**Comment by justinkterry** [comment]
Hey, I'm going to close this due to inactivity. Please let us know if you have any more problems

**Comment by nevertiree** [comment]
Sorry for replying late. Thank you ~
