### ISSUE TITLE
Something strange may be afoot in the observations/rgb arrays for prison and KAZ

### ISSUE THREAD

**Issue by justinkterry** [PettingZoo-Team/PettingZoo#307]
Prison:
The logic inside the top of statement makes no sense to me

KAZ:
The observe function doesn't transpose the pixels3d output anywhere if I understand it correctly

**Comment by justinkterry** [comment]
the human rendering portion of prospector is also very strange

**Comment by weepingwillowben** [comment]
KAZ: The observe function transposes the pixels here: https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/butterfly/knights_archers_zombies/knights_archers_zombies.py#L391

I don't understand the comments about the logic in prison . Can you be more specific?

In prospector, the goal of that wierd logic is to make sure that you don't need a display driver in order to generate rgb_array images with render().

**Comment by justinkterry** [comment]
In prison I was referring to the top of the render function, sorry
