### ISSUE TITLE
How to control the MAgent teams with two different policies ?

### ISSUE THREAD

**Issue by nevertiree** [PettingZoo-Team/PettingZoo#329]
Hi ~

I would like to control the red team and blue team with 2 different RL policies in MAgent environment. 

Should I generate two action sub-lists of them, and merge them into a whole action list, then send the action list to the step() function ?

Are there any build-in bot for benchmark testing between different RL algorithms? Or we need to write a test bot ourselves?

Thank you ~ Have a nice day ~

**Comment by weepingwillowben** [comment]
Hi, I'm glad you are looking at our environments.

The idea you described of generating action sub-lists and merging them is the intended method to train multiple policies in a single environment. Note that the agent names are designed to make this easy: they are formatted `<type>_<id>`, so that you can get the type of an agent with `agent.split("_")[0]`, and then train different policies on different types.

**Comment by nevertiree** [comment]
Thank you for replying ~
