### ISSUE TITLE
Parallel MAgent Adjust Team Sizes

### ISSUE THREAD

**Issue by justinDeu** [PettingZoo-Team/PettingZoo#340]
I've been looking through the constructors for the MAgent environments, particularly Battlefield, and I haven't come up with a simple way to adjust the sizes of each team when using the parallel version. Is there any way to do this? It seems like it defaults to 12v12 without the ability to change it.

**Comment by weepingwillowben** [comment]
I'm glad you found our library.  As it stands right now, some of the MAgent environments are more flexible than others. The battle and combined arms environments automatically adjust the number of agents with the size of the map. The battlefield and gather environment do not. 

What sort of problem are you investigating with MAgent? If you let us know the relevant context, we might be able to help you a bit more.

**Comment by justinDeu** [comment]
We are looking to train collaborative agents through self-play and were interested in using the Battlefield environment but were concerned that having 12v12 may be too complex to learn or hard on our resources such as memory if we were to make copies of the models for each agent. We were looking into scaling down the environment to smaller teams, but we really wanted to maintain the parallel action aspect.

**Comment by weepingwillowben** [comment]
So a few notes:

1. The easiest way to scale down the environment is to use the battle environment with a small map. Perhaps `battle_v2.parallel_env(map_size=20)` gives an acceptable number of agents (of course you can play around with this parameter.
2. The [original MAgent paper](https://arxiv.org/abs/1712.00600) uses parameter sharing to reduce resource usage. Parameter sharing is when each player on a team uses the same neural network models to act, and same optimizer, replay buffer, etc to learn. Since the units on each team in an MAgent environment are homogenous, this makes sense, and it makes learning *much* more stable, more sample efficient, and can produce vastly better results.
3. If you are unsatisfied with the small battle environment, you can configure your own MAgent environment similarly to how is done internally. https://github.com/PettingZoo-Team/PettingZoo/blob/master/pettingzoo/magent/battlefield_v2.py

**Comment by justinDeu** [comment]
Thank you for the direction! We have briefly talked about parameter sharing and may go down that route, but we haven't decided if our algorithms will have some notion of "memory" when playing which could hinder us from utilizing parameter sharing. Still an active avenue of research though.

I actually took your first and third points and combined them to create my own environment based on `battle_v2`. I wanted the ability to create barriers as well. The implementation wasn't that difficult at all once I read over the code and saw how `battlefield_v2` was adding the barriers.

In adjusting the `map_size`, I did notice that teams are not necessarily balanced, however. For example, `battle_v2.parallel_env(map_size=20)` yields a 12v12. According to the formula, `map_size * map_size *0.04` which I believe is meant to determine the team sizes, there should be 16. Looking at the positions generated, it appears that it just so happens that 4 for each team are spawned off the map. Dropping `map_size` to 15 should have 9v9, but it is instead 3v6. It appears that 6 red and 3 blue are spawned off the map.

**Comment by weepingwillowben** [comment]
Yeah, the battle environment just adds agents into the space available, and the result is not necessarily balanced or according to a particular formula. I didn't think this would be a big problem.

**Comment by justinDeu** [comment]
That makes sense. I edited the spawn loops to make consistent teams with our settings. I didn't know if it was intended or a bug, so I wanted to mention it.

**Comment by weepingwillowben** [comment]
If you want to make a PR to make consistent teams for the battle environment, that would definitely be welcomed.

**Comment by weepingwillowben** [comment]
This consistency issue is currently under development.

**Comment by weepingwillowben** [comment]
This fix has been merged into master
