### ISSUE TITLE
Tests cannot be run modularly

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [PettingZoo-Team/PettingZoo#356]
I'm attempting to modify a single environment in PettingZoo (classic/chess_v2). To test my changes, I believe I need to run `pytest pettingzoo/test/pytest_runner.py` and ensure that all tests pass. However, this tests *all* modules in PettingZoo, many of them with additional dependencies (e.g. atari) and many of them fairly time-consuming. Is there a way to only run tests for a specific subset of environments I'm interested in? Using `pytest` to invoke specific tests does not work (`pytest -k "test_chess"`).

**Comment by weepingwillowben** [comment]
Hi, I'm glad you are interested in the pettingzoo environments,

Our intention is that people who wanted to create new environments would use our test functions documented here: https://www.pettingzoo.ml/dev_docs#tests, but not the testing framework in pytest_runner.py. For your use case, I would recommend creating a new file which runs the appropriate tests (in this case, just the api_test).

We haven't really optimize PettingZoo to be modified internally. In fact, we were sort of hoping that environments would not need to be forked because the environment arguments could be changed instead. Could I ask what the modifications you wanted to make for chess are? We would consider supporting your use case as an argument (no guarantees, but we have added quite a few arguments at user request already).

**Comment by weepingwillowben** [comment]
Sorry, I realized there is a way to only run tests for chess:

```
pytest pettingzoo/test/pytest_runner.py::test_module[classic/chess_v2-pettingzoo.classic.chess_v2]
```

**Comment by AbhijeetKrishnan** [comment]
Thank you for getting back to me! I wasn't aware of the `api_test` module. I think using it to create a new test file will be best.

I am trying to make the PettingZoo chess environment compatible with [tf-agents](https://github.com/tensorflow/agents). There is no other project I've found which uses the PettingZoo board game environments to train an RL agent, and I'm trying to do so with standard implementations provided in the tf-agents library. So far, the required changes involve very minimal modifications, such as the datatypes of the action and observation spaces.

**Comment by weepingwillowben** [comment]
Thanks for letting us know what you are doing.

Our intention for making modifications like that is to use a wrapper from [SuperSuit](https://github.com/PettingZoo-Team/SuperSuit/). If your modifications can be implemented with one of the existing wrappers, or easily with the [lambda wrappers](https://github.com/PettingZoo-Team/SuperSuit#lambda-functions), or if neither of those work, then a custom wrapper,  then that would eliminate the need for maintaining a fork.

**Comment by justinkterry** [comment]
Also if you do create a tf-agents supersuit wrapper, please create a PR with it and we'd be happy to merge it.
