### ISSUE TITLE
Atari Pong gets stucked

### ISSUE THREAD

**Issue by Ann-eat-apple** [PettingZoo-Team/PettingZoo#357]
Ok. If I do  `pong_v1`. 
and I make the following actions (player 1 moves at `8`).
`env.step(8, actions)`. 

This will make the game stuck (pong doesn't repawn).

**Comment by weepingwillowben** [comment]
Hi,

I think the following PR is related: https://github.com/PettingZoo-Team/Multi-Agent-ALE/pull/4

The problem here is that player 1 needs to press "fire" in order to serve the ball. And action 8 is not a "fire" action. 

The problem of one layer being able to unilaterally halt play is a general problem in Atari games. What was done to address that before was to penalize the player who is halting play to disincentive it. Somehow pong got overlooked when that change was made. 

Is this solution (assigning negative rewards when player 1 or 2 refuses to serve the ball for a long time) satisfactory?
@justinkterry

**Comment by justinkterry** [comment]
I don't see another sensible alternative to that approach. Is this a problem for other pong games though?

**Comment by weepingwillowben** [comment]
Yes, it is a problem for all the pong games except for the single player one (the one in gym)

**Comment by Ann-eat-apple** [comment]
Thanks for the reply! Is there anyway to force the agent to `fire` if the ball isn't served?

**Comment by weepingwillowben** [comment]
For this game specifically this is possible. You can simply look at the game state, see if the ball is on the screen, and if it isn't, then press fire. 

The problem is doing it in a way that allows the agents to position their paddles before firing, as a human might do in the game. 

Perhaps having a timer (similar to the penalty timer that was implemented in these other environments), and hitting fire when the timer expires, instead of whatever the agent chooses.
