### ISSUE TITLE
quick question: Atari(`full_action_set=False`)

### ISSUE THREAD

**Issue by Ann-eat-apple** [PettingZoo-Team/PettingZoo#360]
Hello again

just one quick question. If I do Atari(`full_action_space =False`), it looks like only the pong returns 6 actions. The other games still have 18 discrete actions. For `boxing_v0`, there shall be reduction, is this correct?

**Comment by weepingwillowben** [comment]
So, I'll note two things:

1. In gym, this argument is true by default. We decided to make it false by default in order to make it easier to write agents which work on multiple environments. 
2. the `full_action_set` is defined by the notion of "minimal actions" from ALE. These aren't documented anywhere, but they are pretty clearly defined in the source, for example: https://github.com/PettingZoo-Team/Multi-Agent-ALE/blob/master/src/games/supported/Boxing.cpp#L61 . Hopefully you can see that in Boxing, all actions are "minimal", so there will be no reduction of the action space.

**Comment by Ann-eat-apple** [comment]
Thanks!
