### ISSUE TITLE
maddpg with Pettingzoo

### ISSUE THREAD

**Issue by dotaking2021** [PettingZoo-Team/PettingZoo#367]
Is there an example of using maddpg with PettingZoo?

The one on the RL-LIB doesn't give a good example of it with PettingZoo.

**Comment by justinkterry** [comment]
MADDPG doesn't really work. Don't use it.

**Comment by dotaking2021** [comment]
@justinkterry , do you know any Multi-agent algorithm that's easy to implement? Such as QMIX etc that already incorporate with the PettingZoo?

**Comment by justinkterry** [comment]
Parameter sharing:


https://link.medium.com/ew08hEsPsfb

**Comment by dotaking2021** [comment]
Yes, I also cite that. But I do need another non-parameter sharing algorithm for comparison. I am wondering if there anything that I can use such as QMix which you paper compare against, so that I can run and compare it, and to show they bad they are, and how strong the parameter sharing method is, @justinkterry ,

**Comment by justinkterry** [comment]
What PettingZoo environments are you working on? and is this for a paper to a journal/conference?

**Comment by dotaking2021** [comment]
I am working with https://www.pettingzoo.ml/magent, yes, this is a paper to conference.

**Comment by justinkterry** [comment]
So there's a few alternatives to parameter sharing. The simplest is fully independent learning, where each agent learns its own policy wholy independently. This can be done easily in RLlib for instance, but has tractability issues. All the other methods you could realistically hope for that might work are in the pymarl and pymarl2 repos, however neither have native PettingZoo support. You should however be able to add PettingZoo support to them fairly easily if you want (and if you do please create a PR and @ me)

**Comment by weepingwillowben** [comment]
MADDPG (and many similar MARL algorithms) are a poor fit for MAgent. This is because of the quadratic complexity with the  number of agents (in MADDPG, the observation of each agent is stacked together to form the critic's observation). So it only is efficient for small maps.

Independent learning both scales poorly (a separate network needs to be trained for each agent), and has very serious non-convergence properties. 

This is why the MAgent paper uses exclusively parameter sharing for its demo. 

QMIX builds upon parameter sharing and centralized critic methods by sharing policies while also using a centralized state to better estimate agent values. However, in MAgent there is no clear centralized state to utilize. 

I'm not quite sure what the solution is. There are certainly ideas in the literature somewhere, but I'm not super familiar with them and I don't know of any convincing.

**Comment by justinkterry** [comment]
Hey I'm going to close this due to inactivity

**Comment by msclar** [comment]
Oh no... do you know of other papers that specifically model the behavior of other agents? I found this one https://arxiv.org/abs/1705.08926, but it appears to be very similar to MADDPG.

**Comment by TylerJamesMalloy** [comment]
Has anyone had any luck with MADDPG in the classic environments? I am having a lot of trouble with it, even trying to add in some aspects of planning and search.

**Comment by justinkterry** [comment]
MADDPG _does not work_.
