### ISSUE TITLE
Observations are the same for different agents in Atari games?

### ISSUE THREAD

**Issue by quantumiracle** [PettingZoo-Team/PettingZoo#423]
Hi, 

I'm trying to use the Pettingzoo Atari games for test, but I found that the observations returned from `env.step()` function under the parallel_env wrapper are always the same for the two agents, e.g. in Boxing or Pong games. However, if I want to use the same model for agents on both sides, it cannot work without modifying the model. Is there any support for observation transformation (for both image and RAM) from one perspective of the agent to another one, such that the returned observations from `env.step()` can be different, i.e. they are from the same agent perspective?

**Comment by RyanNavillus** [comment]
Hi, thanks for raising this issue. Atari games only have one perspective, the pixels that you see on the screen. There isn't any support for mirroring the observations because that would require custom recoloring and image manipulation code for every Atari game.

If you want to use one model to control either side, you probably need to look into something called agent indication. Agent indication augments the observation with information that indicates which agent the model should be controlling at that timestep. For example, for a vector observation, you could add a single bit that denotes whether it is player 1's turn or player 2's turn. Ideally, the agent should be able to learn this signal and use it when selecting an action.

We have one type of agent indication for Atari games implemented in SuperSuit: https://github.com/PettingZoo-Team/SuperSuit#included-multi-agent-only-functions
 
 You can apply it to an environment with:
 `env = agent_indicator_v0(env)`

**Comment by quantumiracle** [comment]
Thanks for your quick reply. I understand the difficulty of pixel mirroring for each Atari game. In this [SlimeVolley](https://github.com/hardmaru/slimevolleygym) environment they provide this kind of transformation for both image and RAM observation, not sure if it's useful for you as a reference. But I will try with the agent indication first.

Anyway, thanks for your great work in this repo!

**Comment by quantumiracle** [comment]
Oh, I just realize one problem, that the agent indication might not be able to work with a specific two-agent self-play setup. Think about that if I only update the model from agent 1's perspective (with indicator has value 0) and its experience, and agent 2 also use this model but a previous checkpoint. Agent 2's model is overwritten periodically from agent 1's model. Then for this model to be applied on agent 2, it sees observations with its indication part being 1 (agent 1 has indicator value 0 and agent 2 has 1), the model never sees observations with indication part as 1 (since it only uses agent 1's experience to learn) in its learning process. Thus the model will  not directly work on agent 2 even with this indicator addition. A slight modification to make it work could be training the model also with agent 2's experience.

**Comment by RyanNavillus** [comment]
Right, one solution is to train the model on both sides for each iteration of your self-play, as you suggested.

@benblack769 Do you have a solution on hand for self-play with agent indication?

**Comment by stringtheorys** [comment]
The agent indication seems to be helpful for the atari games where there are image inputs

But for the classical problems like connect 4, checkers, go and chess, for example, the agent_indicator throws an error.
`AssertionError: agent_indicator space must be 1d, 2d, or 3d Box or Discrete, was Dict(action_mask:Box(0, 1, (7,), int8), observation:Box(0, 1, (6, 7, 2), int8))`

Do you have any recommendations of what to do? 
I was considering passing an additional input to the neural network of the player

Thanks

**Comment by benblack769** [comment]
Classic games do not need agent indication. The observation is carefully constructed to be symmetric no mater which player you are playing and closely matches the observations described in the alphazero paper: https://arxiv.org/pdf/1712.01815.pdf. The board is not constructed as black and white and top to bottom, but your side vs opponents side, and your peices vs opponents peices. This is pretty much an optimal version of agent indication.

**Comment by benblack769** [comment]
@quantumiracle As for an agent indication method for atari I have on hand, I would look at this one for inspiration:

```python
def InvertColorAgentIndicator(env):
    def modify_obs(obs, agent):
        num_agents = len(env.possible_agents)
        agent_idx = env.possible_agents.index(agent)
        if num_agents == 2:
            if agent_idx == 1:
                rotated_obs = 255 - obs
            else:
                rotated_obs = obs
        elif num_agents == 4:
            rotated_obs = (255*agent_idx)//4 + obs

        indicator = np.zeros((2, )+obs.shape[1:],dtype="uint8")
        indicator[0] = 255 * agent_idx % 2
        indicator[1] = 255 * ((agent_idx+1) // 2) % 2
        return np.concatenate([obs, rotated_obs, indicator], axis=0)
    env = ss.observation_lambda_v0(env, modify_obs)
    env = ss.pad_observations_v0(env)
    return env
```
This observation contains
1. The original observation
2. A flipped observation (so that the conv kernels will have different edges for different players), or a rotated observation for 4 players.
3. A binary indicator.

I'm not sure if the `pad_observations_v0` is still needed. I think that was fixed in the latest version of Supersuit

**Comment by benblack769** [comment]
Note that there is no guarantee this is the optimal version of agent indication, in some of my tests, I got better performance by *not* including the original observation. Just a hodgepodge of ideas.

**Comment by quantumiracle** [comment]
@benblack769 Thanks for providing your solution. Also, is there any solution if using RAM observation rather than image? The simple solution mentioned by @RyanNavillus  (`env = agent_indicator_v0(env)`) seems to work for both RAM and image. I'm also wondering about the difference of performances when only using either the observation flipping or adding the binary indicator, rather than using them both. It seems to me only using binary indicator already provides the complete information for the model to differentiate between different agent perspectives, while flipping the observation may improve the performance since it changes more in the observation thus makes it easier for the model to pay attention to agent perspective.

**Comment by benblack769** [comment]
So I have done a couple experiments with the RAM instead of the image (you can just do `space_invaders.env(obs_type="ram")` to create the environment). However, the performance was not significantly better than with the images, so I didn't look much deeper. It is much faster to train, and can be trained easily on CPU however, so I would recommend it for quick experiments. 

I think your speculation about performance of the method is mostly in line with my own. One important thing to note is if you are using a shallow neural network like the 4 layer DQN nature paper network for images, or a 2 layer Mujoco network for RAM then the ease by which convolution filters in the early layers can extract information is critical. And flipping the observation creates different edges and activates different filters (espeically with relu activations).

**Comment by jkterry1** [comment]
I'm closing this, please let us know if you have any more problems
