### ISSUE TITLE
EnvLogger Functionality

### ISSUE THREAD

**Issue by dissendahl** [PettingZoo-Team/PettingZoo#73]
Opening this up as a separate discussion threat for some question related to the EnvLogger and functionality testing that just came up in my head.

@weepingwillowben: 

1. In general, what's the EnvLogger supposed to do? 

2. I briefly read, that the logger is used to log if step() or observe() is called before initially reset() is called. In general, couldn't this be made obsolete by calling reset() right from the init().

3. What is test_api supposed to do? Intuitively I thought it only tests if an environment complies with the common API design. But judging from reading it, it also tests internal functionality, such as (e.g. [here](https://github.com/PettingZoo-Team/PettingZoo/blob/76694b5580edf5596849035ddc84c4143d8e3821/pettingzoo/tests/api_test.py#L224) ). I suggest letting test_api test against everything defined in the AECEnv (as opposed to logic defined in inheriting classes), e.g. return value types, legal call orders, etc. 
For that to be user friendly (hence drive repo adoption), those expectations you test against should be outlined upfront in AECEnv.

4. Reading test_api.py as well as test_chess.py, I was wondering if you are familiar with test frameworks (e.g. unittest, pytest). They could be helpful if you want structured testing.

Best
Clemens

**Comment by weepingwillowben** [comment]
We are rethinking large parts of the project due to these points you are bringing up. Hopefully by the end, the EnvLogger should be gone, and the API test should be greatly simplified, as we will no longer be expecting the environments to do as much error checking.

Keeping better documentation about environment expectations, refractoring the tests, and allowing external contributors to easily use the tests are continuing goals, but are secondary to the major refactoring that is being planned.

I think @justinkterry should have invited you to our slack channel to discuss this in more depth?

**Comment by dissendahl** [comment]
@weepingwillowben  Alright, I just joined.
